export const ADD_TO_MOVIES = "ADD_TO_MOVIES";
export const UPDATE_MOVIES = "UPDATE_MOVIES";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const UPDATE_MOVIE_PREFERENCES = "UPDATE_MOVIE_PREFERENCES";
